[package]
name="lox"
version="0.1.0"
edition="2021"
rust-version="1.80"

[dependencies]
log="0.4.22"                        # logging
env_logger="0.11.0"                 # logging
lox_macro={path="./libs/lox_macro"}
